# Generated by Django 2.2.4 on 2019-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerText', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='About')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='AllFront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='AllFront/Logo')),
                ('headerText', models.CharField(max_length=255)),
                ('movieInto', models.URLField()),
                ('footText', models.TextField()),
                ('newsletterText', models.CharField(max_length=200)),
                ('imageTesti', models.ImageField(upload_to='AllFront/TestiImage')),
                ('imageReservations', models.ImageField(upload_to='AllFront/ReservationsImage')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AllFront',
                'verbose_name_plural': 'AllFronts',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbLink', models.URLField()),
                ('twLink', models.URLField()),
                ('instaLink', models.URLField()),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.CreateModel(
            name='StepIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'StepIndex',
                'verbose_name_plural': 'StepIndexs',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('openHours', models.TimeField()),
                ('closeHours', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WorkingHours',
                'verbose_name_plural': 'WorkingHourss',
            },
        ),
    ]
