# Generated by Django 2.2.6 on 2019-10-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_bannerresto'),
        ('configuration', '0002_banner'),
    ]

    operations = [
    ]
