# Generated by Django 2.2.6 on 2019-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
