# Generated by Django 2.2.6 on 2019-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='image',
            field=models.ImageField(default='', upload_to='Image_resto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='Image_resto'),
        ),
    ]
