# Generated by Django 2.2.6 on 2019-10-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_menujour'),
    ]

    operations = [
        migrations.AddField(
            model_name='menujour',
            name='categroie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='categorie_menu_jour', to='resto.Categorie'),
            preserve_default=False,
        ),
    ]
