# Generated by Django 2.2.6 on 2019-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_menu_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
