# Generated by Django 2.2.6 on 2019-10-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_menujour_categroie'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menujour',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
