# Generated by Django 2.2.6 on 2019-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelle',
            name='image',
            field=models.ImageField(default='myImage.png', upload_to='Pesonelle/'),
            preserve_default=False,
        ),
    ]
