# Generated by Django 2.2.6 on 2019-10-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heure_reserver', to='reservation.Heure'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jour_reserver', to='reservation.Jour'),
        ),
    ]
