# Generated by Django 2.2.6 on 2019-10-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191008_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
