# Generated by Django 2.2.6 on 2019-10-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191008_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heure',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jour',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
