# Generated by Django 2.2.6 on 2019-10-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191009_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='jour',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nbre_reservation',
            field=models.CharField(max_length=50),
        ),
    ]
