# Generated by Django 2.2.6 on 2019-10-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20191009_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TableMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('heure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heure_dispo', to='reservation.Heure')),
                ('jour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jour_dispo', to='reservation.Jour')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_possible', to='reservation.Person')),
            ],
        ),
    ]
